export const UPLOAD_VIDEOS='UPLOAD_VIDEOS';
export const GET_UPLOADED_VIDEOS='GET_UPLOADED_VIDEOS';
export const DELETE_UPLOADED_VIDEOS='DELETE_UPLOADED_VIDEOS';
export const EDIT_UPLOADED_VIDEOS='DELETE_UPLOADED_VIDEOS';
export const IS_LOADING='IS_LOADING';
